# Site settings
title: smellsfishy
author: fishb6nes
email: fishb6nes@noreply.github.com
url: https://smellsfishy.com
description: Delicious graphics programming with a dash of gamedev on the side.
favicon: smellsfishy.png

# Build settings
remote_theme: riggraz/no-style-please
theme_config:
  appearance: "undefined"
  back_home_text: "../"
  date_format: "%Y年%m月%d日"
  show_description: true
sass:
  style: :compressed
plugins:
  - jekyll-feed
  - jekyll-seo-tag
